language: ruby

cache:
  - bundler
  - pip

sudo: false

# If this makes things too slow we may want to find an alternative to awscli
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - |
    if [[ "$(ruby -v)" =~ "ruby 2.2" ]]; then
      gem install bundler -v "1.17.3"
    else
      gem update --system
      gem install bundler
    fi
  # Can't upload coverage data without these
  - |
    if [[ -n $COVERAGE ]] && \
       [[ -z "$AWS_ACCESS_KEY_ID" || \
          -z "$AWS_SECRET_ACCESS_KEY" || \
          -z "$AWS_BUCKET" || \
          -z "$CC_TEST_REPORTER_ID" ]]; then
      echo "Missing config for coverage, not running." >&2
      unset COVERAGE
    fi
  - |
    if [[ -n "$COVERAGE" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter

      pip3 install --user awscli

      export S3_BUILD_PATH=s3://$AWS_BUCKET/$TRAVIS_BUILD_NUMBER
      export S3_JOB_PATH=$S3_BUILD_PATH/$TRAVIS_JOB_NUMBER
    fi

before_script:
  - if [[ -n "$COVERAGE" ]]; then ./cc-test-reporter before-build; fi

script:
  - pushd skylight-core
  - bundle exec rake
  - SKYLIGHT_DISABLE_AGENT=true COVERAGE_DIR=coverage-disabled-agent bundle exec rake
  - popd
  - bundle exec rake
  - SKYLIGHT_DISABLE_AGENT=true COVERAGE_DIR=coverage-disabled-agent bundle exec rake

after_script: |
  if [[ -n "$COVERAGE" && "$TRAVIS_TEST_RESULT" == 0 ]]; then
    aws s3 cp coverage/.resultset.json $S3_JOB_PATH/coverage.json
    aws s3 cp coverage-disabled-agent/.resultset.json $S3_JOB_PATH/disabled-agent-coverage.json
    aws s3 cp skylight-core/coverage/.resultset.json $S3_JOB_PATH/core-coverage.json
    aws s3 cp skylight-core/coverage-disabled-agent/.resultset.json $S3_JOB_PATH/core-disabled-agent-coverage.json
  fi

env:
  global:
    - SKYLIGHT_ENABLE_TRACE_LOGS=true
    - SKYLIGHT_REQUIRED=true
    - SKYLIGHT_TEST_DIR=/tmp
    - RAILS_ENV=development
    - EMBEDDED_HTTP_SERVER_TIMEOUT=30
    - WORKER_SPAWN_TIMEOUT=15
    - COVERAGE=true

stages:
  - sanity
  - test # matrix builds go here
  - extra
  - wrapup

rvm:
  - 2.2
  - 2.5

gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.sinatra-1.4.x
  - gemfiles/Gemfile.sinatra-2.0.x
  - gemfiles/Gemfile.grape
  # Declared manually in the matrix
  # - gemfiles/Gemfile.sinatra-edge
  # - gemfiles/Gemfile.rails-edge

jobs:
  fast_finish: true

  exclude:
    # We already do this in the sanity stage.
    # NOTE: Specifying the stage here makes this not actually work. Seems ok to
    #   leave it off since the `include` takes precedence.
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.2.x

  include:
      # Make sure basic tests pass and do CodeClimate while we're at it
    - stage: sanity
      rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.2.x
    # Older Rails
    - stage: extra
      rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - stage: extra
      rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.1.x
    # Newer Ruby
    - stage: extra
      rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-5.2.x
    # Newer Rails
    - stage: extra
      rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-edge
    # Test old Tilt version (with Rails since Sinatra doesn't like old Tilt)
    - stage: extra
      rvm: 2.5
      env:
        - TILT_VERSION=1.4.1
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - stage: extra
      rvm: 2.5
      env:
        - SEQUEL_VERSION=4.34.0 # Some changes were made in 4.35.0
      gemfile: gemfiles/Gemfile.sinatra-1.4.x
    # Mongo Integration
    - stage: extra
      rvm: 2.5
      env:
        - TEST_MONGO_INTEGRATION=true
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: mongodb
    - stage: extra
      rvm: 2.5
      env:
        - TEST_MONGO_INTEGRATION=true
        - MONGOID_VERSION="~> 4.0"
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: mongodb
    # Elasticsearch Integration
    - stage: extra
      rvm: 2.5
      env:
        - TEST_ELASTICSEARCH_INTEGRATION=true
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: elasticsearch
      before_script:
        - sleep 10
    # Sidekiq Integration
    - stage: extra
      rvm: 2.5
      env:
        - SIDEKIQ_VERSION=4.2.10
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - stage: extra
      rvm: 2.5
      env:
        - SIDEKIQ_VERSION=none
      gemfile: gemfiles/Gemfile.rails-5.1.x
    # Sinatra
    - stage: extra
      rvm: 2.5
      gemfile: gemfiles/Gemfile.sinatra-edge
    # Grape
    - stage: extra
      rvm: 2.5
      env:
        - GRAPE_VERSION="~> 0.13.0"
      gemfile: gemfiles/Gemfile.grape
    - stage: extra
      rvm: 2.5
      env:
        - GRAPE_VERSION="~> 1.1.0"
      gemfile: gemfiles/Gemfile.grape
    - stage: extra
      rvm: 2.5
      env:
        # there are significant architectural changes between 1.1 and 1.2
        - GRAPE_VERSION="~> 1.2.0"
      gemfile: gemfiles/Gemfile.grape
    - stage: extra
      rvm: 2.5
      env:
        - GRAPE_VERSION=edge
      gemfile: gemfiles/Gemfile.grape
    # AMS
    # Default AMS is currently 0.10.0
    - stage: extra
      rvm: 2.5
      env:
        - AMS_VERSION="~> 0.8.3"
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - stage: extra
      rvm: 2.5
      env:
        - AMS_VERSION="~> 0.9.5"
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - stage: extra
      rvm: 2.5
      env:
        - AMS_VERSION=edge
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - stage: wrapup
      install: # Do nothing
      before_script: # Do nothing
      script: |
        if [[ -n "$COVERAGE" ]]; then
          aws s3 sync $S3_BUILD_PATH artifacts
          # Convert coverage format
          find artifacts -name *coverage.json | xargs -I % ./cc-test-reporter format-coverage -t simplecov -o coverage/% %
          # Sum coverages
          ./cc-test-reporter sum-coverage coverage/artifacts/**/*.json
          # We don't need to check build status because we won't get here if the builds didn't succeed
          ./cc-test-reporter upload-coverage
        else
          echo "Skipping coverage due to missing config." >&2
        fi
      after_script: # Do nothing

  allow_failures:
    # Testing edge is nice, but it probably shouldn't kill the build
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.sinatra-edge
    - gemfile: gemfiles/Gemfile.rails-edge
    - env:
        - GRAPE_VERSION=edge
    - env:
        - AMS_VERSION=edge

notifications:
  webhooks:
    urls: https://tilde.slack.com/services/hooks/travis?token=N5Dc2tov6aTfOjXK1VOXlxiS
    on_success: change
    on_failure: always
