language: ruby
cache: bundler

script: ./spec.sh

env:
  global:
    - SKYLIGHT_ENABLE_TRACE_LOGS=true
    - RAILS_ENV=development
    - STANDALONE_WORKER_SPEC_TIMEOUT=15
    - EMBEDDED_HTTP_SERVER_TIMEOUT=30
    - WORKER_SPAWN_TIMEOUT=15
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -
    - SKYLIGHT_DISABLE_AGENT=true

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0

gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
# - gemfiles/Gemfile.rails-edge

matrix:
  exclude:
    # As far as I can tell, Magnum wants the env, public doesn't
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
      env:
        - SKYLIGHT_ENABLE_TRACE_LOGS=true
        - RAILS_ENV=development
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x

# TODO: We may want to bring back rails-edge and add to allow_failures list

notifications:
  webhooks:
    urls: https://tilde.slack.com/services/hooks/travis?token=N5Dc2tov6aTfOjXK1VOXlxiS
    on_success: change
    on_failure: always
