language: ruby
cache: bundler
sudo: false

before_install:
  - gem install bundler
  - |
    if [[ -n "$CODECLIMATE_REPO_TOKEN" ]]; then
      export CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
    fi

before_script:
  - if [[ -n "$CODECLIMATE_REPO_TOKEN" ]]; then ./cc-test-reporter before-build; fi

script:
  - pushd skylight-core
  - bundle exec rake
  - popd
  - bundle exec rake

after_script: |
  if [[ -n "$CODECLIMATE_REPO_TOKEN" ]]; then
    ./cc-test-reporter sum-coverage -p2 coverage/.resultset.json skylight-core/coverage/.resultset.json
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  fi

env:
  global:
    - SKYLIGHT_ENABLE_TRACE_LOGS=true
    - SKYLIGHT_REQUIRED=true
    - SKYLIGHT_TEST_DIR=/tmp
    - RAILS_ENV=development
    - EMBEDDED_HTTP_SERVER_TIMEOUT=30
    - WORKER_SPAWN_TIMEOUT=15
  matrix:
    # The first one is intentionally empty in order to run without any extra env vars
    -
    - SKYLIGHT_DISABLE_AGENT=true

rvm:
  - 2.2
  - 2.5

gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.sinatra-1.4.x
  - gemfiles/Gemfile.sinatra-2.0.x
  - gemfiles/Gemfile.grape
  # Declared manually in the matrix
  # - gemfiles/Gemfile.sinatra-edge
  # - gemfiles/Gemfile.rails-edge

matrix:
  fast_finish: true
  exclude:
    # We don't need to test so many disabled combinations
    - rvm: 2.2
      env: SKYLIGHT_DISABLE_AGENT=true

  include:
    # Older Rails
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.0.x
      # Empty env is required otherwise Travis defaults to SKYLIGHT_DISABLE_AGENT=true
      env:
        -
    # Newer Rails
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-5.1.x
      # Empty env is required otherwise Travis defaults to SKYLIGHT_DISABLE_AGENT=true
      env:
        -
    # Separate Code Climate coverage run, sort of duplicate of normal Rails 5 job
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-5.1.x
      env:
        # CODECLIMATE_REPO_TOKEN
        - secure: "dGdkneTJSwPJ8QXfUhhG6fSxGpZPgX5pidYm3cA6o4VsErAF3m5r5cyTO54Swzb9m0Ib2mLfqJtcd0n+0IJFTRxGQe98H0QDpBE8UAf0H8AjXwHmjYpVzSxm/iPZDIuDTkDsfFLxaQ1NbOiSm2joUoU70icNyIAArvN3bh/fMpM="
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-edge
      # Empty env is required otherwise Travis defaults to SKYLIGHT_DISABLE_AGENT=true
      env:
        -
    - rvm: 2.5
      env:
        - SKYLIGHT_DISABLE_AGENT=true
      gemfile: gemfiles/Gemfile.rails-edge
    # Test old Tilt version (with Rails since Sinatra doesn't like old Tilt)
    - rvm: 2.5
      env:
        - TILT_VERSION=1.4.1
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5
      env:
        - SEQUEL_VERSION=4.34.0 # Some changes were made in 4.35.0
      gemfile: gemfiles/Gemfile.sinatra-1.4.x
    # Mongo Integration
    - rvm: 2.5
      env:
        - TEST_MONGO_INTEGRATION=true
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: mongodb
    - rvm: 2.5
      env:
        - TEST_MONGO_INTEGRATION=true
        - MONGOID_VERSION="~> 4.0"
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: mongodb
    # Elasticsearch Integration
    - rvm: 2.5
      env:
        - TEST_ELASTICSEARCH_INTEGRATION=true
      gemfile: gemfiles/Gemfile.rails-4.2.x
      services: elasticsearch
      before_script:
        - sleep 10
    # Sinatra
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.sinatra-edge
      # Empty env is required otherwise Travis defaults to SKYLIGHT_DISABLE_AGENT=true
      env:
        -
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.sinatra-edge
      env:
        - SKYLIGHT_DISABLE_AGENT=true
    # Grape
    - rvm: 2.5
      env:
        - GRAPE_VERSION=0.13.0
      gemfile: gemfiles/Gemfile.grape
    - rvm: 2.5
      env:
        - GRAPE_VERSION=edge
      gemfile: gemfiles/Gemfile.grape
    # AMS
    # Default AMS is currently 0.10.0
    - rvm: 2.5
      env:
        - AMS_VERSION="~> 0.8.3"
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5
      env:
        - AMS_VERSION="~> 0.9.5"
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5
      env:
        - AMS_VERSION=edge
      gemfile: gemfiles/Gemfile.rails-4.2.x

  allow_failures:
    # Testing edge is nice, but it probably shouldn't kill the build
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.sinatra-edge
    - gemfile: gemfiles/Gemfile.rails-edge
    - env:
        - GRAPE_VERSION=edge
    - env:
        - AMS_VERSION=edge

notifications:
  webhooks:
    urls: https://tilde.slack.com/services/hooks/travis?token=N5Dc2tov6aTfOjXK1VOXlxiS
    on_success: change
    on_failure: always
